/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package phat.sensors.camera;

import java.awt.image.BufferedImage;
import phat.sensors.accelerometer.*;
import phat.sensors.SensorData;

/**
 * Representates information generated by a simulated accelerometer 
 * (AccelerometerControl).
 * 
 * @author Pablo
 */
public class CameraSensorData implements SensorData {    
    private BufferedImage image;
    private int width;
    private int heigh;
    private int type;
    private float fps;

    public CameraSensorData(float fps, BufferedImage image, int width, int heigh, int type) {
        this.image = image;
        this.width = width;
        this.heigh = heigh;
        this.type = type;
        this.fps = fps;
    }

    public BufferedImage getImage() {
        return image;
    }

    public int getWidth() {
        return width;
    }

    public int getHeigh() {
        return heigh;
    }

    public int getType() {
        return type;
    }

    public float getFps() {
        return fps;
    }
}
