/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package phat.sensors.accelerometer;

import phat.sensors.SensorData;

/**
 * Representates information generated by a simulated accelerometer 
 * (AccelerometerControl).
 * 
 * @author Pablo
 */
public class AccelerationData implements SensorData {
    private float interval;
    private float x;
    private float y;
    private float z;

    public AccelerationData(float interval, float x, float y, float z) {
        this.interval = interval;
        this.x = x;
        this.y = y;
        this.z = z;
    }

    public float getInterval() {
        return interval;
    }

    public float getX() {
        return x;
    }

    public float getY() {
        return y;
    }

    public float getZ() {
        return z;
    }
}
